sonar.organization=nogameno-life
sonar.projectKey=NogameNo-life_study-notes-ios

sonar.sources=StudyNotes/StudyNotes
sonar.tests=StudyNotes/StudyNotesTests
sonar.coverageReportPaths=sonarqube-generic-coverage.xml